name: unisub_video_processing
description: "A Flutter plugin for video processing on macOS"
version: 0.0.1
homepage: https://github.com/yourcompany/unisub_video_processing

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: VideoProcessingPlugin